### ISSUE TITLE
👋 Dan!

### ISSUE THREAD

**Issue by chantastic** [learnreact/reactcontext.com#1]
Hi @gaearon!

You'd asked that I ping you when I got to work on a Context reference. This is the reference.

I'm actively working on refining the language and reworking the sections. But these are the basic concepts and assumptions I plan to share.

I'm eager to modify, add, or remove anything that you think might make this a better resource for those new to Context.

🤗

**Comment by gaearon** [comment]
How to comment inline? There's no easy way unless it's a PR

**Comment by chantastic** [comment]
Sorry for the false start. I've broken up all of the sections into individual PRs:

#2 A "shit" Example
#3 Create, Consume, and Provide Context
#4 Provide value
#5 Authoring Style
#6 Data Distribution, not state management
#7 A Mental Model
#8 Does Context "replace" or "deprecate" Redux

And sorry for the delay. Some family health issues have my attention a little divided.

Thanks again for your interest in this.
